Improve json check to include date

diff --git a/.github/workflows/json-validation.yml b/.github/workflows/json-validation.yml
--- a/.github/workflows/json-validation.yml
+++ b/.github/workflows/json-validation.yml
@@ -1,5 +1,9 @@
 name: Validate JSON Formatting
 on: [pull_request, workflow_dispatch]
+
+env:
+  DATA_JSON_PATH: "./Packages/com.mattshark.openflight/Runtime/data.json"
+
 jobs:
   verify-json-validation:
     runs-on: ubuntu-latest
@@ -10,3 +14,19 @@ jobs:
         env:
           INPUT_SCHEMA: ./Packages/com.mattshark.openflight/Runtime/data_schema.json
           INPUT_JSONS: ./Packages/com.mattshark.openflight/Runtime/data.json
+      
+      - name: Extract JSON Date
+        uses: sergeysova/jq-action@v2
+        id: json_date
+        with:
+          cmd: "jq '.[\"JSON Date\"]' $DATA_JSON_PATH"
+
+      - name: Check if Date is latest
+        run: |
+          printf -v date '%(%Y-%m-%d)T\n' -1
+          if [ $date != ${{ steps.json_date.outputs.value }} ]; then
+            echo value=false >> $GITHUB_OUTPUT
+            echo "::error file=$DATA_JSON_PATH, line=3::Date not set to the latest date"
+            exit 1
+          fi
+          echo value=true >> $GITHUB_OUTPUT
